
version: "3.7"

networks:
    app:
        driver: bridge
        name: microservices
    local:
        driver: host

volumes:
    openthon_rabbitmq:

services:
    openthon_rabbitmq:
        image: rabbitmq:3.8-management
        container_name: openthon_rabbitmq
        hostname: openthon_rabbitmq
        cap_drop:
            - NET_ADMIN
            - SYS_ADMIN
        environment:
            HOSTNAME: rabbitmq_hostname_container
            RABBITMQ_NODENAME: rabbitmq
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - openthon_rabbitmq:/bitnami
        ports:
            - "4369:4369"
            - "5672:5672"
            - "25672:25672"
            - "15672:15672"
        expose:
            - "15672"
            - "5672"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
        deploy:
            resources:
                limits:
                    memory: 2048M
                    cpus: "1"
                reservations:
                    memory: 2048M

    openthon_worker:
        image: openthon_worker
        container_name: openthon_worker
        hostname: openthon_worker
        build:
            context: .
            dockerfile: deploy/worker/Dockerfile
        environment:
            {BROKER_URL}

    openthon_web:
        image: openthon_web
        container_name: openthon_web
        hostname: openthon_web
        build:
            context: .
            dockerfile: deploy/web/Dockerfile
